name: Run Login Tests

on:
  workflow_dispatch:

jobs:
  login-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Clear previous Allure results
        run: rm -rf ./allure-results/*

      - name: Run Contact Us Test with Allure reporter
        run: npx playwright test __tests__/login/loginTests.spec.js --reporter=line,allure-playwright || true

      - name: Install Allure CLI
        if: always()
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        if: always()
        run: allure generate ./allure-results --output ./allure-report --clean

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          destination_dir: allure-report/${{ github.run_id }}

      - name: Upload Allure Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-login
          path: ./allure-report

      - name: Send Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: PlaywrightBot
          SLACK_ICON_EMOJI: ':robot_face:'
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
          SLACK_MESSAGE: |
            *Login Tests:* `${{ job.status }}`  
            - Triggered by: `${{ github.actor }}`
            - Branch: `${{ github.ref_name }}`
            - [View Logs and Download Allure Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - :rocket: [Live Allure Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure-report/${{ github.run_id }}/)