name: Daily Playwright Tests

on:
  schedule:
    - cron: '0 4 * * *'   # 7:00 AM IL (UTC+3)
    - cron: '0 16 * * *'  # 7:00 PM IL (UTC+3)
  workflow_dispatch:

jobs:
  Daily-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Clear previous Allure results
        run: rm -rf ./allure-results/*

      - name: Run Playwright tests with Allure reporter
        run: npx playwright test --reporter=line,allure-playwright || true

      - name: Install Allure CLI
        if: always()
        run: npm install -g allure-commandline
      
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate ./allure-results --output ./allure-report --clean
      
      - name: Upload Allure Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
