name: Daily Playwright Tests

on:
  schedule:
    - cron: '0 4 * * *'  # 7:00 AM IL time (UTC+3)
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/upload-artifact@v2


      - name: Setup Node.js
        uses: actions/upload-artifact@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Clear previous Allure results
        run: rm -rf ./allure-results/*

      - name: Run Playwright tests with Allure reporter
        run: npx playwright test --reporter=line,allure-playwright

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: |
          allure generate ./allure-results --output ./automation-allure-report --clean

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./automation-allure-report

      # - name: Notify Slack (Optional)
      #   if: always()
      #   run: |
      #     curl -X POST -H 'Content-type: application/json' \
      #     --data '{"text":"✅ Allure report is ready. Download from GitHub Actions → Artifacts tab."}' \
      #     ${{ secrets.SLACK_WEBHOOK_URL }}


